name: svpro
description: "Ứng dụng tiện ích cho sinh viên."
publish_to: 'none'

version: 1.0.3+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  go_router: ^16.0.0
  flutter_lints: ^6.0.0
  shared_preferences: ^2.5.3
  http: ^1.4.0
  intl: ^0.20.2
  flutter_local_notifications: ^19.3.1
  timezone: ^0.10.1
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  flutter_svg: ^2.2.0
  web_socket_channel: ^3.0.3
  timeago: ^3.7.1
  table_calendar: ^3.2.0
  flutter_localizations:
    sdk: flutter
  visibility_detector: ^0.4.0+2
  scrollable_positioned_list: ^0.3.8
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/icon/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"