// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6xlFgmxRgVD88A5cXIGYr84LxSjUBODk',
    appId: '1:860440377687:web:8646306443624721df2612',
    messagingSenderId: '860440377687',
    projectId: 'svpro-26929',
    authDomain: 'svpro-26929.firebaseapp.com',
    storageBucket: 'svpro-26929.firebasestorage.app',
    measurementId: 'G-BKQNFP7KGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDITMOjZO52Tywm84gm_2YwNDTp_g5t2NE',
    appId: '1:860440377687:android:c15b2138b6bb54addf2612',
    messagingSenderId: '860440377687',
    projectId: 'svpro-26929',
    storageBucket: 'svpro-26929.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnAcRpmqdQWdkM2V64_f0a1V5mt-mg0Uk',
    appId: '1:860440377687:ios:058a9df7c61fc033df2612',
    messagingSenderId: '860440377687',
    projectId: 'svpro-26929',
    storageBucket: 'svpro-26929.firebasestorage.app',
    iosBundleId: 'com.vantu.svpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnAcRpmqdQWdkM2V64_f0a1V5mt-mg0Uk',
    appId: '1:860440377687:ios:058a9df7c61fc033df2612',
    messagingSenderId: '860440377687',
    projectId: 'svpro-26929',
    storageBucket: 'svpro-26929.firebasestorage.app',
    iosBundleId: 'com.vantu.svpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6xlFgmxRgVD88A5cXIGYr84LxSjUBODk',
    appId: '1:860440377687:web:4c1566e7dbbf54e4df2612',
    messagingSenderId: '860440377687',
    projectId: 'svpro-26929',
    authDomain: 'svpro-26929.firebaseapp.com',
    storageBucket: 'svpro-26929.firebasestorage.app',
    measurementId: 'G-Q70709LMLJ',
  );
}
